: NIP SWAP DROP ;
: TUCK SWAP OVER ;

: FALSE 0 ;
: TRUE FALSE INVERT ;
: NEGATE INVERT 1+ ;

: / /MOD NIP ;
: MOD /MOD DROP ;
: <> = INVERT ;
: >= < INVERT ;
: <= > INVERT ;
: 0<> 0= INVERT ;
: 0>= 0< INVERT ;
: 0<= 0> INVERT ;
